### ISSUE TITLE
How to get access token?

### ISSUE THREAD

**Issue by jomei** [roperzh/medium-sdk-elixir#2]
Hello!

How I can get an access token, that your talking about in your doc
> Since all Medium requests must be made with an integration token, you need to create a new client associated with that token in order to perform requests

?

From Medium I get only client_id and secret_key. 
Thank you.

**Comment by roperzh** [comment]
Hey @jomei,

If you are testing the library or building something for your own, I'd recommend you to use a [Self-issued access token](https://github.com/Medium/medium-api-docs#22-self-issued-access-tokens) which you can get from your Medium profile as described on the link.

If you are building an app or service, you will have to implement a [browser based authentication](https://github.com/Medium/medium-api-docs#21-browser-based-authentication), if you are familiar with OAuth this should be easy. This library [provides](https://github.com/roperzh/medium-sdk-elixir/blob/master/lib/medium.ex#L34-L72) some functions to help with that. If you are having a hard time, maybe you can check [this library](https://github.com/scrogson/oauth2)

I will improve the documentation soon, but you should be good to go.
